gg.jte.developmentMode=true
spring.application.name=petclinic

server.port=8085

# messages.properties
typeMismatch.date=Invalid date format
typeMismatch.birthDate=Invalid date format

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.hibernate.ddl-auto=none

logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.springframework.cache.interceptor=TRACE
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE